baseURL = 'http://localhost/aws-mahjong/'
languageCode = 'ja-jp'
title = 'AWS麻雀'
ignoreLogs = ['sections-none-/']

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/thingsym/hugo-theme-techdoc"

[params]
  menu_style = "slide-menu"
  ordersectionsby = "weight"
  rental_form_url = "https://docs.google.com/forms/d/e/1FAIpQLSf3kwiPJiMAA3ymezgxUu-GL04xqXodnxjzMoDtDWJeymcjHA/viewform?usp=dialog"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
